name: Update CI
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [update_ci]
jobs:
  release:
    name: Update API
    runs-on: ubuntu-18.04
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js v12
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Update notes summary
        run: node update-data.mjs
