name: Update CI
on:
  schedule:
    - cron: "0 1 * * 1"
  push:
    branches: [main]
  repository_dispatch:
    types: [update_ci]
  workflow_dispatch:
jobs:
  release:
    name: Update API
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Update notes summary
        run: node update-data.mjs
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":card_file_box: Update data"
      - name: Dispatch AnandChowdhary/everything update
        uses: benc-uk/workflow-dispatch@v1
        with:
          repo: AnandChowdhary/everything
          workflow: api.yml
          token: ${{ secrets.WORKFLOW_DISPATCH_TOKEN }}
